### ISSUE TITLE
Neologin Nodejs support

### ISSUE THREAD

**Issue by sahmmie** [safudex/neologin#44]
I think there should be a need for neologin to support Nodejs runtime

**Comment by corollari** [comment]
Interesting request, if you don't mind a few questions about it:
- What use-case do you have in mind?
- How would the widget work in a nodejs environment?
- Given that the host machine running the nodejs script will have full access to all the data being processed by the script, I believe that the protection offered by neologin (dApps don't have access to user's private keys) would be broken, is that right?

**Comment by sahmmie** [comment]
- In a case where Nodejs is used as the backend for a mobile application and a web application.  Mobile applications would need to use neologin, so therefor their wallet login would be handled from the backend.

- there won't be a widget in the nodejs environment, the library would accept the user's neologin credentials just like the widget does.

- There's a possibility that the protection is broken, but the user's private key is still safe, the only con would be that users neologin credentials might be visible to the dapp.

I hope this is clear enough

**Comment by sahmmie** [comment]
Should there be so many cons for the nodejs support, then I think neologin should consider support for mobile applications, just like flutter, Java, and so on

**Comment by corollari** [comment]
I see, so, if I understand it properly, getting a user to sign a transaction in a mobile dapp would require the following steps:
1. Mobile app requests neologin credentials from the user
2. Credentials get sent to the nodejs backend
3. Nodejs backend gets user's private key from neologin's servers and signs transactions with it

Is that correct, or are you thinking of something else that could potentially protect the user's key from getting known by the dapp?

Also, some neologin users have 2FA enabled on their accounts, how do you think that should be handled? Get the mobile app to collect the 2FA code as well?

**Comment by sahmmie** [comment]
hmmm, I really can't think of a better way of keeping away the user's private away from the dapp,
yes, the app should collect the 2FA code as well.
I think a module(library) could be developed for mobile apps and it could be integrated into the app when in development

**Comment by corollari** [comment]
Well, it's already possible to do that, so I'm not opposed to creating an sdk that just makes it easier. I'll give it a go and report back after some testing.

**Comment by sahmmie** [comment]
okay, I'll close this then.
Hoping to hear from you soon

**Comment by corollari** [comment]
If you don't mind, I'll reopen this in order to use it to track progress on this front.

**Comment by corollari** [comment]
While I was planning to work on this, I haven't had the time available and going forward it seems like I won't either, so given that this is not an essential feature I think it's better to close it.
